menubar: false
toolbar:
  - styleselect | bold italic | undo redo | uploadimage | link media
plugins:
  - image
  - link
  - uploadimage
  - media
language: ko_KR
statusbar: false
media_alt_source: false
media_poster: false
media_live_embeds: true
